### PR TITLE
Save metadata of genData in attributes

### PR DESCRIPTION
**Pull request by agrueneberg**

### CODE REVIEW

**Comment by gdlc** [comment]
I am wondering if it would not be better to store dataType as an attribute,
e.g.,

x<-1:10
attributes(x)<-list(name='peter',birthdate=date())
attributes(x)


Apparently attributes can be any list, we can set

attributes(genData)<-list(fileIn=,data=date() ) # it  will be nice to store
full-path-name of the pedfile used to create it and the date.
attrbitues(genData@geno)<-list(dataType=,...)

help(attributes) clarifies that some attributes (colnames, rownames, dim,
nrow, ncol) are treated in a somehow special fashion in R....

Gustavo

**Comment by agrueneberg** [comment]
I'm not sure if attributes would have any benefit. They seem brittle as we already have a formal object.
I realized that I put the slot on the wrong object, though. I think it should be on `genData`, as a way to determine the structure of the original PED file, not the structure of DMatrix. If I want to know what, I could just call `vmode` on one the the `ff` objects. We could also have a convenience function like this for both `rDMatrix` and `cDMatrix`:
```R
vmode.rDMatrix <- function (x) {
    vmode(x[[1]])
}
```

**Comment by gdlc** [comment]
It is not very clear to me what will be the conceptual difference between
attributes and slots in R.

I typically think of slots as 'instance fields' that is you have a class,
it has instance fields, when you create an object you set particular values
for those fields.  This in R can be achieved with use of slots. It seems to
me that the only difference between that and attributes, is that attributes
seem to be used to describe properites and not the data itself, slots seem
to be reserved for the data...

Gustavo

**Comment by agrueneberg** [comment]
I changed the code to store the metadata in attributes. I decided to group together `path` and `dataType` into `origFile`. Like I said above, I think `dataType` makes the most sense on `genData`, as a pointer with what data type the file was imported.

**Pull request merged**
